### ISSUE TITLE
New relevant package

### ISSUE THREAD

**Issue by KronosTheLate** [christiankral/EE.jl#9]
I just announced my first package in [this discourse post](https://discourse.julialang.org/t/ann-announcing-circuitcomponentrounding-jl/62496). In researching it's need, I have stumbled over this package. I was just thinking that my package is likely relevant to whoever might use this one. So I would simply like to invite to do one of the following:
1) Add a reference to my package, to make it more discoverable to the relevant people
2) Add it as a dependency, and export its functionality directly.

The second option is viable, as the package is very small and lightweight. I am however still open to suggestions for API changes, and so this should possibly wait until I release a 1.0.0 version.

**Comment by christiankral** [comment]
I do like option 1 promoting your package. I will add a reference to your package.

**Comment by KronosTheLate** [comment]
Sounds good ^_^

**Comment by christiankral** [comment]
Added CircuitComponentRounding.jl to README.md 4cb2fa67cdaf5355640d2b3d93a9488798740663
